### PR TITLE
Lint 1.7.0 recipe

### PR DESCRIPTION
**Pull request by marcoesters**
Needed for pre-commit, which will be used for the anaconda-linter development

# Package Info

Home/doc URL: https://ekalinin.github.io/nodeenv/
Dev URL: https://github.com/ekalinin/nodeenv

### CODE REVIEW

**Review by cbouss — COMMENTED** [review]
LGTM, but you can remove abs.yaml before merging and check that s390x builds.

**Review by varlackc — COMMENTED** [review]
Since `pip` is is part of the required dependencies we should add `pip` to the `test section` we should `require` `pip` and use `pip check` on the `command` section 
https://github.com/AnacondaRecipes/nodeenv-feedstock/blob/8324e264b876952cf116202a54b3f24f802e2100/recipe/meta.yaml#L34&L46

**Review by skupr-anaconda — APPROVED** [review]

**Comment by marcoesters** [comment]
> Since `pip` is is part of the required dependencies we should add `pip` to the `test section` we should `require` `pip` and use `pip check` on the `command` section https://github.com/AnacondaRecipes/nodeenv-feedstock/blob/8324e264b876952cf116202a54b3f24f802e2100/recipe/meta.yaml#L34&L46

Added `pip check` - thanks!

**Review by varlackc — APPROVED** [review]
LGTM

**Pull request merged**
